DROP TABLE IF EXISTS book;
DROP TABLE IF EXISTS author;
DROP TABLE IF EXISTS genre;

CREATE TABLE author(
    id IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE genre(
    id IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE book(
    id IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR(255),
    author_id BIGINT NOT NULL,
    genre_id BIGINT NOT NULL,
    FOREIGN KEY (author_id) REFERENCES author (id) ON DELETE CASCADE,
    FOREIGN KEY (genre_id) REFERENCES genre (id) ON DELETE CASCADE
);
